# Generated by Django 3.0.6 on 2020-07-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(default='', max_length=50, verbose_name='支付编号'),
        ),
    ]
